
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const NKA = Noto_Kufi_Arabic({ subsets: ["latin"] });

export const metadata = {
  title: "Elbashamdars - البشمدرس",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${NKA.className}`}>
      <ToastContainer className={'text-right font-bold'} />
      <NextTopLoader />
        <div className="max-w-[1360px] relative text-black dark:text-white">
          {children}
        </div>
        </body>
    </html>
  );
}
