import Header from "@/app/_component/header/header";
import Footer from "../_component/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className='max-w-[1360px] relative'>
      <Header/>
      {children}
      <Footer/>
    </div>
  );
}
